### ISSUE TITLE
CUSTOM_MAT_COLOR_FORMATS 

### ISSUE THREAD

**Issue by alexandra-toder** [h2qutc/angular-material-components#148] opened 2020-11-27 14:22 UTC
the CUSTOM_MAT_COLOR_FORMATS  doesn't work. I can't set only hex format

**Comment by h2qutc** [comment] 2020-12-06 04:49
@alexandra-toder  CUSTOM_MAT_COLOR_FORMATS is used to customize the input. You should have done something like that:  

```
//'rgb' | 'hex' | 'hex6' | 'hex3' | 'hex4' | 'hex8'
const CUSTOM_MAT_COLOR_FORMATS: MatColorFormats = {
  display: {
    colorInput: 'hex8'
  }
}

@NgModule({
  imports: [
    CommonModule,
    ...
  ],
  providers: [
    { provide: MAT_COLOR_FORMATS, useValue: CUSTOM_MAT_COLOR_FORMATS }
  ],
  ...
})
export class DemoColorpickerModule { }
```
Can you provide more details so that I can help you ?  I close the issue, if the issue is not resolved, feel free to reopen.

**Closed by h2qutc** 2020-12-06 04:49 UTC
