### ISSUE TITLE
4.x version not showing Time format in 12 hour format. even if enableMeridian  is true

### ISSUE THREAD

**Issue by himanshu2487** [h2qutc/angular-material-components#125] opened 2020-09-28 02:34 UTC
Thanks for the component.

4.x version not showing Time format in 12 hour format. even if enableMeridian  is true

![image](https://user-images.githubusercontent.com/47127127/94384758-f6634880-0108-11eb-8305-7c41e836c08c.png)
After selection

![image](https://user-images.githubusercontent.com/47127127/94384841-30344f00-0109-11eb-9a44-995dab6eed69.png)

**Comment by himanshu2487** [comment] 2020-10-06 04:22
Can anyone suggest how to fix this .

**Comment by h2qutc** [comment] 2020-10-06 09:17
@himanshu2487  The bug is reproductible, a new version will be released within 2 days to fix that.

**Comment by cklam2** [comment] 2020-10-09 13:53
We worked around the issue by passing a custom parse format. Which would only work when you do not use moment.js. But a fix in the lib would be much nicer

```
// Format used for the Intl format functions
const fullDateTimeOptions = { year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric' }; // Can also add seconds
const CUSTOM_DATE_FORMATS = Object.assign({}, NGX_MAT_NATIVE_DATE_FORMATS, {
  parse: { dateInput: fullDateTimeOptions },
  display: { dateInput: fullDateTimeOptions }
});

// In your module:
{ provide: NGX_MAT_DATE_FORMATS, useValue: CUSTOM_DATE_FORMATS }
```

**Comment by h2qutc** [comment] 2020-10-12 10:39
@himanshu2487 @cklam2  After verifying, I think that it is not a bug. It is a comportement of the component. In fact, we use a provider called NGX_MAT_DATE_FORMATS to define how the component parse and display the selected date. 
`export declare type NgxMatDateFormats = {
    parse: {
        dateInput: any;
    };
    display: {
        dateInput: any;
        monthYearLabel: any;
        dateA11yLabel: any;
        monthYearA11yLabel: any;
    };
};`

So you have created a custom format to respond your demand. Feel free to check [demo stackblitz ](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-angular10), I did an example by using custom formats that works for Moment.js
You can also check the [demo and documentation](https://h2qutc.github.io/angular-material-components/datetimepicker) for details.

**Closed by h2qutc** 2020-10-12 10:39 UTC

**Comment by himanshu2487** [comment] 2020-10-12 22:46
@h2qutc thanks for looking ,  worked around from @cklam2  is working good for me . Thanks for help guys
