### ISSUE TITLE
missing peer dependency

### ISSUE THREAD

**Issue by thorek** [h2qutc/angular-material-components#93] opened 2020-08-09 21:57 UTC
I get 
npm install --save  @angular-material-components/file-input
npm WARN @angular-material-components/file-input@2.0.0 requires a peer of @angular/platform-browser@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/file-input@2.0.0 requires a peer of @angular/common@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/file-input@2.0.0 requires a peer of @angular/core@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/file-input@2.0.0 requires a peer of @angular/forms@0.0.0-NG but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/file-input@2.0.0 requires a peer of @angular/material@0.0.0-PLACEHOLDER but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/file-input@2.0.0 requires a peer of @angular/cdk@0.0.0-PLACEHOLDER but none is installed. You must install peer dependencies yourself.
npm WARN @angular-material-components/file-input@2.0.0 requires a peer of tslib@0.0.0-TSLIB but none is installed. You must install peer dependencies yourself.

It installs 2.0.0 - this should work with Angular 9 - but I cannot solve the strange peer dependency.

**Comment by bramn** [comment] 2020-11-09 08:43
I think this is a duplicate of #53 .

**Comment by h2qutc** [comment] 2020-12-05 07:30
@thorek  Please check the latest version to resolve the problem. 
Version 4.x is for Angular 10, 5.x is for Angular 11.

**Closed by h2qutc** 2020-12-05 07:30 UTC
