### ISSUE TITLE
You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by sucheep-s** [h2qutc/angular-material-components#117] opened 2020-09-14 17:32 UTC
I have tried to use ngx-mat-datetime-picker and it is not working. But for mat-datepicker, it works normally.

- Angular version : 10.1

- material version : 10.1

- angular-material-components/datetime-picker - 4.0.3

Following is my code.

`          <mat-form-field appearance="outline" fxFlex>
            <mat-label>Transaction Date</mat-label>
            <input
              matInput
              [ngxMatDatetimePicker]="transDatePicker"
              formControlName="trans_date"
              required
              readonly
            />
            <mat-datepicker-toggle
              matSuffix
              disabled
              [for]="transDatePicker"
            ></mat-datepicker-toggle>
            <ngx-mat-datetime-picker #transDatePicker [showSpinners]="showSpinners" [showSeconds]="showSeconds"
              [stepHour]="stepHour" [stepMinute]="stepMinute"
              [touchUi]="touchUi" [color]="color" [enableMeridian]="enableMeridian">
            </ngx-mat-datetime-picker>
          </mat-form-field>`

When I try to load the page, datetime-picker appears but following error appears on console.

`ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (subscribeTo.js:27)
    at subscribeToResult (subscribeToResult.js:11)
    at MergeMapSubscriber._innerSub (mergeMap.js:59)
    at MergeMapSubscriber._tryNext (mergeMap.js:53)
    at MergeMapSubscriber._next (mergeMap.js:36)
    at MergeMapSubscriber.next (Subscriber.js:49)
    at Observable._subscribe (subscribeToArray.js:3)
    at Observable._trySubscribe (Observable.js:42)
    at Observable.subscribe (Observable.js:28)
    at MergeMapOperator.call (mergeMap.js:21)`

Is there anything I miss ?

**Comment by Ongrieh** [comment] 2020-09-14 21:47
Any different than #99 ??
Duplicate of #99 ??

**Comment by h2qutc** [comment] 2020-09-17 08:49
@sucheep-s For the version 4.0.3, you have to use Angular Material 10.2.1. Can you try and let me know if it's fixed ?

**Comment by baodongle** [comment] 2020-09-17 10:19
@h2qutc The version 4.0.3 only worked with Angular Material 10.2.0, not with 10.2.1. When I update Angular Material from 10.2.0 to 10.2.1, this issue happened.

**Comment by irkreja** [comment] 2020-09-18 01:44
Hi, Facing same problem here with angular 10.1.1, angular/material 10.2.1 and datetime-picker 4.0.4.

**Comment by BootsSiR** [comment] 2020-09-22 12:23
Angular 10.1.2  Angular Matieral 10.2.1 and datetime-picker 4.0.4 and I'm seeing this error as well

**Comment by RoyAndersen** [comment] 2020-09-22 13:02
I'm having the same issue. 
* Angular 10.1.2
* Material 10.2.2 (also with Material 10.2.1)
* datetime-picker 4.0.4

**Comment by h2qutc** [comment] 2020-09-22 20:14
Hi All, a version v4.0.5 has already been released. That version works fine with Angular >=10.1.2 and Angular Material >=10.2.1
Feel free to check it out.
Thanks all for your support

**Closed by h2qutc** 2020-09-22 20:14 UTC

**Comment by trantoi99** [comment] 2021-06-24 04:53
I have this issue in my application (Angular 11.x) and i need some solutions.
Thanks for all.

**Comment by h2qutc** [comment] 2021-06-24 09:35
@trantoi99 If you use Angular 11, you can try datetime-picker version 5.x.

**Comment by jayatulsiani** [comment] 2021-09-09 16:52
What version is compatible for angular 7 versions?
