### ISSUE TITLE
Angular 11 compatibility

### ISSUE THREAD

**Issue by achablowski** [h2qutc/angular-material-components#153] opened 2020-12-08 09:06 UTC
Hello,

Is it possible to update the component to ensure compatibility with angular 11 ?

Thanks in advance

**Comment by luisferreira90** [comment] 2020-12-09 15:00
I have a problem when using this with Angular 10 and 11. After opening the component, I can't close it and have to refresh the page. I can't remember the exact problem, because I reverted to Angular 9.

**Comment by h2qutc** [comment] 2020-12-09 15:04
@achablowski The version 5.x has been released for Angular 11. Feel free to check it out.

**Comment by h2qutc** [comment] 2020-12-09 15:07
@luisferreira90 Can you let me know the version with which you have problem with Angular 10, 11 plz?
The version 5.x is for Angular 11, 4.x for Angular 10. 
Thank for your support.

**Comment by luisferreira90** [comment] 2020-12-09 15:08
Hi, @h2qutc,
Thank you for your quick reply! I will check it out later and then come back to you. Thanks.

**Comment by mfabioe** [comment] 2020-12-09 15:31
cant upgrade to angular material/cdk 10.2.x also. angular-material-components/file-input is at 4.0.1
                  Package "@angular-material-components/file-input" has an incompatible peer dependency to "@angular/cdk" (requires "~10.0.1", would install "10.2.7").
                  Package "@angular-material-components/file-input" has an incompatible peer dependency to "@angular/material" (requires "~10.0.1", would install "10.2.7").

**Comment by luisferreira90** [comment] 2020-12-09 15:53
@h2qutc 
I tested it now, and it still happens with version 5 and Angular 11. As soon as the component loads, I get this message:

`ERROR TypeError: Cannot read property 'selectionChanged' of undefined
    at MatDatepickerInput._registerModel (datepicker.js:2970)
    at MatDatepickerInput.set matDatepicker [as matDatepicker] (datepicker.js:3178)
    at Object.ngOnChangesSetInput [as setInput] (core.js:2401)
    at setInputsForProperty (core.js:10032)
    at elementPropertyInternal (core.js:9079)
    at ɵɵproperty (core.js:15103)
    at DatepickerComponent_Template (datepicker.component.html:17)
    at executeTemplate (core.js:8689)
    at refreshView (core.js:8558)
    at refreshComponent (core.js:9711)`

I also get this one:

`ERROR TypeError: this._datepickerInput._getThemePalette is not a function
    at NgxMatDatetimePicker.get color [as color] (angular-material-components-datetime-picker.js:4434)
    at NgxMatDatetimePicker._setColor (angular-material-components-datetime-picker.js:4901)
    at NgxMatDatetimePicker._openAsDialog (angular-material-components-datetime-picker.js:4784)
    at NgxMatDatetimePicker.open (angular-material-components-datetime-picker.js:4711)
    at DatepickerComponent_Template_div_click_0_listener (datepicker.component.html:2)
    at executeListenerWithErrorHandling (core.js:15610)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15645)
    at HTMLDivElement.<anonymous> (platform-browser.js:582)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28183)`

The component is opened correctly and I can interact with it normally, but I can't close it and need to refresh the page.

**Comment by h2qutc** [comment] 2020-12-09 16:01
> @h2qutc 
> 
> I tested it now, and it still happens with version 5 and Angular 11. As soon as the component loads, I get this message:
> 
> 
> 
> `ERROR TypeError: Cannot read property 'selectionChanged' of undefined
> 
>     at MatDatepickerInput._registerModel (datepicker.js:2970)
> 
>     at MatDatepickerInput.set matDatepicker [as matDatepicker] (datepicker.js:3178)
> 
>     at Object.ngOnChangesSetInput [as setInput] (core.js:2401)
> 
>     at setInputsForProperty (core.js:10032)
> 
>     at elementPropertyInternal (core.js:9079)
> 
>     at ɵɵproperty (core.js:15103)
> 
>     at DatepickerComponent_Template (datepicker.component.html:17)
> 
>     at executeTemplate (core.js:8689)
> 
>     at refreshView (core.js:8558)
> 
>     at refreshComponent (core.js:9711)`
> 
> 
> 
> I also get this one:
> 
> 
> 
> `ERROR TypeError: this._datepickerInput._getThemePalette is not a function
> 
>     at NgxMatDatetimePicker.get color [as color] (angular-material-components-datetime-picker.js:4434)
> 
>     at NgxMatDatetimePicker._setColor (angular-material-components-datetime-picker.js:4901)
> 
>     at NgxMatDatetimePicker._openAsDialog (angular-material-components-datetime-picker.js:4784)
> 
>     at NgxMatDatetimePicker.open (angular-material-components-datetime-picker.js:4711)
> 
>     at DatepickerComponent_Template_div_click_0_listener (datepicker.component.html:2)
> 
>     at executeListenerWithErrorHandling (core.js:15610)
> 
>     at wrapListenerIn_markDirtyAndPreventDefault (core.js:15645)
> 
>     at HTMLDivElement.<anonymous> (platform-browser.js:582)
> 
>     at ZoneDelegate.invokeTask (zone-evergreen.js:399)
> 
>     at Object.onInvokeTask (core.js:28183)`
> 
> 
> 
> The component is opened correctly and I can interact with it normally, but I can't close it and need to refresh the page.

Which version of angular material you used ? Is that 11.0.2 ?

**Comment by h2qutc** [comment] 2020-12-09 16:03
> cant upgrade to angular material/cdk 10.2.x also. angular-material-components/file-input is at 4.0.1
> 
>                   Package "@angular-material-components/file-input" has an incompatible peer dependency to "@angular/cdk" (requires "~10.0.1", would install "10.2.7").
> 
>                   Package "@angular-material-components/file-input" has an incompatible peer dependency to "@angular/material" (requires "~10.0.1", would install "10.2.7").

I will try to fix it and release a new version soon.

**Comment by luisferreira90** [comment] 2020-12-09 16:24
> Which version of angular material you used ? Is that 11.0.2 ?

I am using Angular Material 11.0.2, Angular 11.0.3 and Datetime Picker 5.0.1

**Comment by mfabioe** [comment] 2020-12-09 16:46
> > cant upgrade to angular material/cdk 10.2.x also. angular-material-components/file-input is at 4.0.1
> > ```
> >               Package "@angular-material-components/file-input" has an incompatible peer dependency to "@angular/cdk" (requires "~10.0.1", would install "10.2.7").
> > 
> >               Package "@angular-material-components/file-input" has an incompatible peer dependency to "@angular/material" (requires "~10.0.1", would install "10.2.7").
> > ```
> 
> I will try to fix it and release a new version soon.

do you think it is safe to force update of angular material, meaning you will only adjust requirements from ~10.0.1 to ^10.0.1?

**Comment by h2qutc** [comment] 2020-12-10 02:30
@mfabioe The version 4.0.2 of file-input has already been released. Can you test that please?

**Comment by h2qutc** [comment] 2020-12-10 04:02
@luisferreira90  I can not manage to reproduce the bug. Can you try to remove node_modules and re-download to ensure that the good versions are used in your project. The version 5.0.2 has already been released. Feel free to check it out.  You can also upgrade Angular from 11.0.3 to 11.0.4. 
Thanks for your support.

**Comment by mfabioe** [comment] 2020-12-10 12:26
@h2qutc it worked. thanks!

**Closed** 2020-12-10 12:53 UTC
